Solution/SchoolHealthManagement/Controllers/SupplierPaymentDetailMOEController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using SchoolHealthManagement.Models;

namespace SchoolHealthManagement.Controllers
{
    public class SupplierPaymentDetailMoeController : Controller 
    {
        private readonly string _strConnection;

        public SupplierPaymentDetailMoeController()
        {
            _strConnection = ConfigurationManager.ConnectionStrings["UsedConnection"].ConnectionString; 
        }

        public ActionResult Index()
        {
            SupplierPaymentMOE model = new SupplierPaymentMOE();

            List<SupplierPaymentMOE> paymentRequestList = getSavedSupplierPaymentMOEs();

            
            ViewBag.SupplierPaymentRequestList = paymentRequestList;
            ViewBag.Month = GetMonthsString();
            ViewBag.Year = GetResentYears(model.Year.ToString());
            ViewBag.Banks = GetBanks();
            

            ViewBag.GrantTotal = (from od in model.PaymentSummary select od.TotalAmount).Sum();

            return View(model);
        }
       
        public JsonResult GetSupplierPaymentSummery(int year, string month)
        {
            // Here you are free to do whatever data access code you like
            // You can invoke direct SQL queries, stored procedures, whatever 
            List<SupplierPaymentSummary> lstPayment = new List<SupplierPaymentSummary>();
            List<SelectListItem> lstProvinces = GetProvinces();
            string strConnection = ConfigurationManager.ConnectionStrings["UsedConnection"].ConnectionString;
            using (var conn = new SqlConnection(strConnection))
            using (var cmd = conn.CreateCommand())
            {

                conn.Open();
                cmd.CommandText = $"EXEC GET_SupplerPaymentSummery {year},'{month}'";
                SqlDataAdapter da = new SqlDataAdapter(cmd);
                DataTable dt = new DataTable();
                da.Fill(dt);

                foreach (DataRow dr in dt.Rows)
                {
                    SupplierPaymentSummary row = new SupplierPaymentSummary();
                    string prov = Convert.ToString(dr["ProvinceID"]);
                    row.Province = lstProvinces.FirstOrDefault(p => p.Value == prov)?.Text;
                    row.ProvinceId = prov;
                    row.Year = Convert.ToInt32(dr["Year"]);
                    row.Month = Convert.ToString(dr["Month"]);
                    row.TotalAmount = Convert.ToDecimal(dr["ProvinceTotal"]);

                    lstPayment.Add(row);
                }
            }
            var grantTotal = lstPayment.Sum(x => x.TotalAmount);
            return Json(new { data = lstPayment, grantTotal = grantTotal }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult GetPaymentDetailMoe(string model)
        {
            try
            {
                var filters = JsonConvert.DeserializeObject<List<FilterModel>>(model);
                List<SupplierPaymentRequestDetail> lstPayment = new List<SupplierPaymentRequestDetail>();
                var zonedataDic = new Dictionary<string, SupplierDetailZoneLevel>();
                var year = filters.Select(x => x.Year).FirstOrDefault();
                var month = filters.Select(x => x.Month).FirstOrDefault();
                using (var conn = new SqlConnection(_strConnection))
                using (var cmd = conn.CreateCommand())
                {
                    conn.Open();
                    foreach (var filter in filters)
                    {
                        cmd.CommandText =
                            $"EXEC GET_SupplerPaymentDetails {filter.Year},'{filter.Month}',{filter.ProvinceId},{false}";
                        SqlDataAdapter da = new SqlDataAdapter(cmd);
                        DataTable dt = new DataTable();
                        da.Fill(dt);

                        foreach (DataRow dr in dt.Rows)
                        {
                            SupplierPaymentRequestDetail row = new SupplierPaymentRequestDetail();
                            row.CensorsID = Convert.ToString(dr["CensusID"]);
                            row.SupplierId = Convert.ToInt32(dr["SupplierId"]);
                            row.SupplierName = Convert.ToString(dr["SupplierName"]);
                            row.Amount = Convert.ToDecimal(dr["Amount"]);
                            row.SupplierPaymentReqHeaderId = Convert.ToDecimal(dr["supplierPaymentReq_HeaderId"]);
                            row.BankAccountNo = Convert.ToString(dr["BankAccountNo"]);
                            row.BankName = Convert.ToString(dr["BankName"]);
                            row.BranchName = Convert.ToString(dr["BranchName"]);
                            row.BankCode = Convert.ToString(dr["BankCode"]);
                            row.BranchCode = Convert.ToString(dr["BranchCode"]);
                            row.ZoneName = Convert.ToString(dr["ZoneName"]);
                            row.ProvinceName = Convert.ToString(dr["ProvinceName"]);
                            row.ProvinceId = Convert.ToInt32(dr["ProvinceId"]);
                            row.SupplierPaymentReqDetailId = Convert.ToInt32(dr["SupplierPaymentReq_DetailId"]);

                            lstPayment.Add(row);
                        }
                    }

                    var provinceGroup = lstPayment.GroupBy(x => x.ProvinceName);
                    var returnModel = new SupplierDetailPayModel();
                    returnModel.FullTotal = lstPayment.Sum(x => x.Amount);

                    foreach (var prov in provinceGroup)
                    {
                        var provinceLevel = new SupplierDetailProvinceLevel();
                        provinceLevel.ProvincialTotal = prov.Sum(x => x.Amount);
                        provinceLevel.ProvinceName = prov.Key;
                        var zoneGroup = prov.GroupBy(x => x.ZoneName);
                        foreach (var zone in zoneGroup)
                        {
                            var zoneLevel = new SupplierDetailZoneLevel();
                            zoneLevel.ZoneTotal = zone.Sum(x => x.Amount);
                            zoneLevel.ZoneName = zone.Key;
                            var details = zone.ToList().Select(c => new SupplierPaymentRequestDetailMoe()
                            {
                                Amount = c.Amount,
                                BankName = c.BankName,
                                BankCode = c.BankCode,
                                BranchCode = c.BranchCode,
                                BranchName = c.BranchName,
                                SupplierName = c.SupplierName,
                                BankAccountNo = c.BankAccountNo,
                                CensorsId = c.CensorsID,
                                Year = year,
                                Month = month,
                                ProvinceId = c.ProvinceId,
                                SupplierId = c.SupplierId,
                                SupplierPaymentReqHeaderId = c.SupplierPaymentReqHeaderId,
                                SupplierPaymentReqDetailId = c.SupplierPaymentReqDetailId

                            }).ToList();
                            zoneLevel.SupplierPaymentRequestDetails = details;
                            provinceLevel.SupplierDetailZoneLevel.Add(zoneLevel);
                            zonedataDic.Add(zone.Key, zoneLevel);
                        }
                        returnModel.Detail.Add(provinceLevel);

                    }
                    ViewBag.TableData = zonedataDic;
                    return PartialView("_SupplierPaymentMOEGroupLevel", returnModel);
                }
            }
            catch (Exception e)
            {
                return Json(new { status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult SaveSupplyerPaymentMoe(string model, string chequeNo, string chequeDate)
        {
            try
            {
                var chequeDateConverted = Convert.ToDateTime(chequeDate);
                var savedPayments = JsonConvert.DeserializeObject<List<SupplierPaymentRequestDetailMoe>>(model);

                var grandotal = savedPayments.Sum(x => x.Amount);
                var result = Insert_SupplierPayment_MOE_Header(chequeNo, chequeDateConverted, savedPayments, grandotal);
                if (result)
                {
                    UpdateSupplierPaymentReq_Detail(savedPayments);
                }

                return Json(new { status = true, mes = "Success" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { status = false, mes = e.Message }, JsonRequestBehavior.AllowGet);
            }

        }

        private bool Insert_SupplierPayment_MOE_Header(string chequeNo, DateTime chequeDateConverted, List<SupplierPaymentRequestDetailMoe> savedPayments, decimal grandotal)
        {
            try
            {
                var year = savedPayments.FirstOrDefault()?.Year;
                var month = savedPayments.FirstOrDefault()?.Month;
                var provinceId = savedPayments.FirstOrDefault()?.ProvinceId;

                using (var conn = new SqlConnection(_strConnection))
                {
                    using (var cmd = conn.CreateCommand())
                    {
                        conn.Open();

                        cmd.Parameters.Clear();
                        cmd.CommandText = "Insert_SupplierPayment_MOE_Header";
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@PaymentDate", DateTime.Now);

Solution/SchoolHealthManagement/Views/SupplierPaymentDetailMoe/Index.cshtml
@model SchoolHealthManagement.Models.SupplierPaymentMOE
@{
    ViewBag.Title = "MOE Supplier Payment";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<link href="~/Content/assets/bootstrap/css/bootstrap-table.min.css" rel="stylesheet" />
<style>
    .details_container_table td input[type="password"] {
        border: 1px solid #d0d0d0;
        height: 28px;
        border-radius: 0px;
        margin: 0;
        padding: 0;
        width: 226px;
    }

    .bckl {
        color: #094B75;
        padding-left: 20px;
    }

        .bckl:hover {
            color: #40A8E8;
        }
</style>
<body>
    @if (ViewBag.SuccessMessage != null)
    {
        <div class="SuccessMsg">
            @ViewBag.SuccessMessage
        </div>
    }
</body>
<div class="container">
    <div class="row index-top-box">
        <div class="form-sub-headers">
            <h2>MOE - Supplier Payment</h2>

        </div>
        <table class="details_container_table" style="width: 50%">
            <tbody>
                <tr>
                    <td style="width: 20%; text-align: right">@Html.Label("Year")</td>
                    <td style="width: 30%">
                        @Html.DropDownList("Year")
                        @Html.ValidationMessageFor(model => model.Year)
                    </td>
                </tr>
                <tr>
                    <td style="width: 20%; text-align: right">@Html.Label("Month") </td>
                    <td style="width: 30%">
                        @Html.DropDownList("Month", "Select Month")
                        @Html.ValidationMessageFor(model => model.Month)
                    </td>
                </tr>

            </tbody>
        </table>
        <div class="row col-md-12 hidden" id="provincialReqForMonth">
            <h3>Provincial Requisitions for the Month</h3>
            <p>Provincial forwarded requests for the selected month will be listed in this table.</p>

            <table id="supplyerTable" class="datatable sortable"></table>

            <div class="row">
                <span style="margin-left:519px"> Grand Total <strong style="margin-left:177px" id="grandTotal">@ViewBag.GrantTotal</strong></span>

            </div>

            <div class="row col-md-4">
                <a class="btn btn-success btn-sm" onclick="getAll()">
                    <i class="fa fa-chain"> None Paid Detail</i>
                </a>
                <a class="btn btn-info btn-sm" onclick="getNonePaidAll()">
                    <i class="fa fa-money"> Paid Detail</i>
                </a>
                
            </div>
            <br />
        </div>
        <div class="row clear both"><br /></div><br />
        <div class="row col-md-12 hidden" id="paymentDetail">

            @*<table id="supplyerSummaryTable" class="datatable sortable"></table>*@

            @*<table class="" style="width: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 70%; text-align: right" colspan="3">@Html.Label("Grand Total") </td>
                            <td style="width: 30%; text-align: right">
                                <p id="pstot">@Model.PaymentSummaryTot</p>
                            </td>
                        </tr>
                    </tbody>
                </table>*@
        </div>
        <br />
    </div>
</div>
<script src="~/Content/assets/bootstrap/js/bootstrap-table.min.js"></script>


<script type="text/javascript">

    $(document).ready(function() {

        $("#Month").change(function() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetSupplierPaymentSummery" ,"SupplierPaymentDetailMoe")', // we are calling json method

                dataType: 'json',

                data: { Year: $("#Year").val(), Month: $("#Month").val() },

                success: function(payments) {
                    $("#grandTotal").html(payments.grantTotal);
                    $("#provincialReqForMonth").removeClass('hidden');
                    if (payments.data.length > 0) {
                        $('#supplyerTable').bootstrapTable('destroy');
                        $('#supplyerTable').bootstrapTable({
                            columns: [
                                {
                                    field: 'ProvinceId',
                                    title: 'Province',
                                    visible: false
                                },
                                {
                                    field: 'check',
                                    checkbox: true
                                },
                                {
                                    field: 'Province',
                                    title: 'Province'
                                }, {
                                    field: 'Year',
                                    title: 'Year'
                                }, {
                                    field: 'Month',
                                    title: 'Month'
                                },
                                {
                                    field: 'TotalAmount',
                                    title: 'Total Amount'
                                }
                            ],
                            data: payments.data
                        });

                    } else {
                        $("#grandTotal").html(payments.grantTotal);
                        $('#supplyerTable').bootstrapTable('destroy');
                        $('#supplyerTable').bootstrapTable({
                            columns: [
                                {
                                    field: 'ProvinceId',
                                    title: 'Province',
                                    visible: false
                                },
                                {
                                    field: 'check',
                                    checkbox: true
                                },
                                {
                                    field: 'Province',
                                    title: 'Province'
                                }, {
                                    field: 'Year',
                                    title: 'Year'
                                }, {
                                    field: 'Month',
                                    title: 'Month'
                                },
                                {
                                    field: 'TotalAmount',
                                    title: 'Total Amount'
                                }
                            ],
                            data: payments.data
                        });
                    }
                },
                error: function(ex) {
                    alert('Failed to retrieve rows.' + ex);
                }
            });
        });

    });

    function getAll() {
        var data = $("#supplyerTable").bootstrapTable('getAllSelections');

        if (data.length > 0) {
            $.ajax({
                url: "@Url.Action("GetPaymentDetailMoe", "SupplierPaymentDetailMoe")",
                method: "POST",
                data: { model: JSON.stringify(data) }
            }).done(function(response) {
                if (!response.status) {
                    $("#paymentDetail").removeClass('hidden');
                    $("#paymentDetail").empty();
                    $("#paymentDetail").append(response);

                } else {
                    $("#paymentDetail").addClass('hidden');
                    $("#paymentDetail").empty();
                }

            });
        } else {
            $.alert({
                title: 'Warning!',
                type: 'orange',
                icon: 'fa fa-warning',
                content: 'No recordes are selected!'
            });
        }
    }

    function getNonePaidAll() {
        var data = $("#supplyerTable").bootstrapTable('getAllSelections');

        if (data.length > 0) {
            $.ajax({
                url: "@Url.Action("GetPaidPaymentDetailMoeView", "SupplierPaymentDetailMoe")",
                method: "POST",
                data: { model: JSON.stringify(data) }
            }).done(function(response) {
                if (!response.status) {
                    $("#paymentDetail").removeClass('hidden');
                    $("#paymentDetail").empty();
                    $("#paymentDetail").append(response);

                } else {
                    $("#paymentDetail").addClass('hidden');
                    $("#paymentDetail").empty();
                }

            });
        } else {
            $.alert({
                title: 'Warning!',
                type: 'orange',
                icon: 'fa fa-warning',
                content: 'No recordes are selected!'
            });
        }
    }

</script>

Solution/SchoolHealthManagement/Views/SupplierPaymentDetailMoe/_SupplierPaymentMOEGroupLevel.cshtml
@using Newtonsoft.Json
@model SchoolHealthManagement.Models.SupplierDetailPayModel
<link href="~/Content/assets/bootstrap/css/bootstrap-table.min.css" rel="stylesheet" />
<div class="row col-md-12" id="payGrid">

    <div class="row col-md-12">
        @if (Model.Detail.Any())
        {
            foreach (var supplierDetailProvinceLevel in Model.Detail)
            {
                <div class="row col-md-12 fa-border">
                    <div class="row col-md-12">
                        <span style="margin-left: 40px">Province Name  : <strong> @supplierDetailProvinceLevel.ProvinceName</strong></span>
                    </div>
                    @if (supplierDetailProvinceLevel.SupplierDetailZoneLevel.Any())
                    {
                        <div class="row">
                            @foreach (var zone in supplierDetailProvinceLevel.SupplierDetailZoneLevel)
                            {
                                <div class="row col-md-12">
                                    <div class="row col-md-12">
                                        <span style="margin-left: 80px"> Zone Name : <strong>@zone.ZoneName</strong></span>
                                    </div>
                                    <div class="row col-md-12" style="margin-left: 14px;">
                                        <table id="@zone.ZoneName" class="datatable col-md-12">
                                            <thead>
                                            <tr>
                                                <th data-field="check" data-checkbox="true"></th>
                                                <th data-field="CensorsId">Censors Id</th>
                                                <th data-field="SupplierName">Supplier Name</th>
                                                <th data-field="BankAccountNo">Account No</th>
                                                <th data-field="BankName">Bank Name</th>
                                                <th data-field="BranchName">Branch Name</th>
                                                <th data-field="Amount">Amount</th>
                                            </tr>
                                        </table>


                                    </div>
                                    <div class="row col-md-12">
                                        <span style="margin-left: 717px">Zone Total &emsp;&emsp;&emsp;&emsp;&emsp;<strong style="margin-left: 24px;">@zone.ZoneTotal</strong></span>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                    <div class="row">
                        <span style="margin-left: 717px">Provincial Total &emsp; &emsp; <strong style="margin-left: 30px;">@supplierDetailProvinceLevel.ProvincialTotal</strong></span>
                    </div>
                </div>
                <div class="row clear both"><br/>
                </div><br/>
            }
            <div class="row">
                <span style="margin-left: 711px">Grand Total &emsp;&emsp;&emsp;&emsp;&emsp; <strong style="margin-left: 12px;">@Model.FullTotal</strong></span>
            </div>
        }
    </div>
</div>
<div class="row clear both"><br /></div>
<div class="col-md-12 row">
    <div class="col-md-4">
        <span>Cheque No :</span>   <input type="text" id="chequeNo" class="form-box" style="border: 1px solid #b7b1b1;height: 30px;
    width: 180px"/>
    </div>
    <div class="col-md-4">
        <span>Cheque Date :</span>   <input type="text" id="chequeDate" class="form-box" style="border: 1px solid #b7b1b1;height: 30px;
    width: 180px"/>
    </div>
</div>
<div class="row clear both"><br /><br /></div>
<div class="row">
    <a class="btn btn-info btn-sm" id="payedSave">
        <i class="fa fa-save"> Save</i>
    </a> 
    
</div>
<div class="row clear both"><br /><br /></div>
<script src="~/Content/assets/bootstrap/js/bootstrap-table.min.js"></script>

<script type="text/javascript">
    var  tableData = @Html.Raw(@Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.TableData));

    $(function() {

        $('#payGrid table.datatable').each(function(i, obj) {

            var $table = $(obj).prop('id');
            var data = tableData[$table].SupplierPaymentRequestDetails;
            $('#' + $table).bootstrapTable({ data: data });

        });

        $("#chequeDate").datepicker();
        var n = $(document).height();
        $('html, body').animate({ scrollTop: n }, 2000);

        $("#payedSave").on('click', function() {
            var payedSave = [];
            $('#payGrid table.datatable').each(function(i, obj) {
                var $table = $(obj).prop('id');
                var data = $('#' + $table).bootstrapTable('getAllSelections');
                if (data.length > 0) {
                    $.each(data, function(i, obj) {
                        payedSave.push(obj);
                    });
                }

            });
            var chequeDate = $("#chequeDate").val();
            var chequeNo = $("#chequeNo").val();
            if (payedSave.length > 0) {
                if(chequeDate ==='')
                {
                    $.alert({
                        title: 'Warning!',
                        type: 'orange',
                        icon: 'fa fa-warning',
                        content: 'Cheque Date should not be empty'
                    });
                    return;

                }else if (chequeNo === '') {
                    $.alert({
                        title: 'Warning!',
                        type: 'orange',
                        icon: 'fa fa-warning',
                        content: 'Cheque No should not be empty'
                    });
                    return;
                }
                $.confirm({
                    icon: 'fa fa-spinner fa-spin',
                    title: 'Confirm!',
                    content: 'Are You sure to save the payments ?',
                    buttons: {
                        confirm:
                        {
                            btnClass: 'btn-blue',
                            action: function() {
                                $.ajax({
                                    url: "@Url.Action("SaveSupplyerPaymentMoe", "SupplierPaymentDetailMoe")",
                                    method: "POST",
                                    data: { model: JSON.stringify(payedSave), chequeNo: chequeNo, chequeDate: chequeDate }
                                }).done(function(response) {
                                    if (!response.status) {
                                        $("#paymentDetail").removeClass('hidden');
                                        $("#paymentDetail").empty();
                                        $("#paymentDetail").append(response);

                                    } else {
                                        $("#paymentDetail").addClass('hidden');
                                        $("#paymentDetail").empty();
                                    }

                                });
                            }
                        },
                        cancel: {
                            btnClass: 'btn-red'
                        }
                    }
                });
            } else {
                $.alert({
                    title: 'Warning!',
                    type: 'orange',
                    icon: 'fa fa-warning',
                    content: 'No recordes are selected!'
                });
            }
            });
        

    });
</script>

Solution/SchoolHealthManagement/Views/SupplierPaymentDetailMoe/_SupplierPaymentPaidMOEView.cshtml
@model System.Collections.Generic.List<SchoolHealthManagement.Models.SupplierPaymentRequestPaidDetail>
<h5> Paid Supplier payments</h5>
<div class="row">
    <table id="paid" class="datatable col-md-12">
        <thead>
        <tr>
            <th data-field="PaymentNo">Payment No</th>
            <th data-field="PaymentDateString">Payment Date</th>
            <th data-field="Year">Year</th>
            <th data-field="Month">Month</th>
            <th data-field="BankName">Bank Name</th>
            <th data-field="ChequeNumber">Cheque No</th>
            <th data-field="ChequeDateString">Cheque Date</th>
            <th data-field="Amount">Amount</th>
        </tr>
    </table>
</div>
<br/>
<div class="row col-md-4">
    <a class="btn btn-success btn-sm" id="print">
        <i class="fa fa-file-pdf-o"> Print</i>
    </a> &nbsp; &nbsp;
    <a class="btn btn-info btn-sm" id="export">
        <i class="fa fa-archive"> Export</i>
    </a>
</div>
<br />
<div class="row clear both"></div> <br/>
 <br/>
<script type="text/javascript">
    var data = @Html.Raw(@Newtonsoft.Json.JsonConvert.SerializeObject(@Model));
    $(function() {
        $('#paid').bootstrapTable({ data: data });
        var n = $(document).height();
        $('html, body').animate({ scrollTop: n }, 2000);

        $("#print").on('click', function() {
            var data = $("#supplyerTable").bootstrapTable('getAllSelections');
            var model = JSON.stringify(data);
            var link = "@Url.Action("SupplierPaymentMoePdfGenerate", "SupplierPaymentDetailMoe")?";
            link = link + "model=" + model  ;
            location.href = link;
        });

        $("#export").on('click', function() {
            var data = $("#supplyerTable").bootstrapTable('getAllSelections');
            var model = JSON.stringify(data);
            var link = "@Url.Action("SupplierPaymentMoeTextGenerate", "SupplierPaymentDetailMoe")?";
            link = link + "model=" + model  ;
            location.href = link;
        });
    });
</script>